In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import Imputer
%matplotlib inline
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from scipy import linspace, polyval, polyfit, sqrt, stats, randn, optimize
import statsmodels.api as sm

In [3]:
df1=pd.read_csv('MarathonData.csv',sep=',',na_values=['#NAME?'])
df1

,id,Marathon,Name,Category,km4week,sp4week,CrossTraining,Wall21,MarathonTime,CATEGORY
0,1,Prague17,Blair MORGAN,MAM,132.8,14.434783,NaN,1.16,2.37,A
1,2,Prague17,Robert Heczko,MAM,68.6,13.674419,NaN,1.23,2.59,A
2,3,Prague17,Michon Jerome,MAM,82.7,13.520436,NaN,1.30,2.66,A
3,4,Prague17,Daniel Or lek,M45,137.5,12.258544,NaN,1.32,2.68,A
4,5,Prague17,Luk ? Mr zek,MAM,84.6,13.945055,NaN,1.36,2.74,A
5,6,Prague17,David Pecina,M40,42.2,13.612903,NaN,1.32,2.78,A
6,7,Prague17,Tomas Drabek,M40,89.0,12.594340,NaN,1.38,2.81,A
7,8,Prague17,Jan Rada,M45,106.0,12.694611,NaN,1.41,2.84,A
8,9,Prague17,Tomas Drabek,MAM,70.0,13.770492,ciclista 1h,1.38,2.83,A
9,10,Prague17,martin ?indel ?,M45,84.2,13.365079,NaN,1.35,2.86,A
10,11,Prague17,Maksim Remezau,MAM,93.5,13.200000,NaN,1.42,2.87,A
11,12,Prague17,Jaroslaw Marchewka,M50,65.7,13.362712,NaN,1.40,2.87,A
12,13,Prague17,Tom ? K?e?ek,M45,53.5,14.078947,ciclista 4h,1.37,2.88,A
13,14,Prague17,Ji?، Polcar,M40,84.4,13.836066,NaN,1.41,2.88,A
14,15,Prague17,Denis Wachtl,MAM,76.8,12.943820,NaN,1.44,2.89,A
15,16,Prague17,David Lehnen,MAM,76.1,14.970492,NaN,1.45,2.90,A
16,17,Prague17,Jپrgen Steiner,M55,112.3,12.594393,ciclista 13h,1.44,2.91,A
17,18,Prague17,David Marek,M40,49.7,14.336538,NaN,1.44,2.91,A
18,19,Prague17,Jan Fri?ek,MAM,84.5,12.549505,NaN,1.45,2.93,A
19,20,Prague17,Vlastimil Lys k,MAM,76.7,8.031414,NaN,1.41,2.94,A
20,21,Prague17,Radek Dvo? k,MAM,94.5,11.886792,NaN,1.45,2.99,A
21,22,Prague17,Jind?ich Lisى,M40,67.3,13.239344,NaN,1.50,3.04,B
22,23,Prague17,Carlos Valladares Calvo,M40,59.4,12.638298,NaN,1.50,3.05,B
23,24,Prague17,Jiri Syrovatko,M45,66.1,12.128440,NaN,1.48,3.09,B
24,25,Prague17,Florian Kobler,MAM,67.4,12.878981,NaN,1.52,3.10,B
25,26,Prague17,Jan Ro?ek,NaN,23.8,13.471698,ciclista 5h,-,3.11,B
26,27,Prague17,Cat Simpson,WAM,129.6,12.188088,NaN,1.54,3.12,B
27,28,Prague17,Pavel Hlo?ek,MAM,82.4,11.771429,NaN,1.52,3.14,B
28,29,Prague17,Enrico Ballerin,M45,51.6,13.008403,NaN,1.50,3.15,B
29,30,Prague17,Jaroslav Jur sek,M50,104.9,11.720670,NaN,1.57,3.16,B
...,...,...,...,...,...,...,...,...,...,...
57,58,Prague17,Michel Brucker,MAM,36.3,11.647059,NaN,1.72,3.51,C
58,59,Prague17,Mark Orton,MAM,22.7,12.728972,NaN,1.67,3.52,C
59,60,Prague17,Hannes Lilljequist,M40,45.2,11.024390,NaN,1.77,3.52,C
60,61,Prague17,Szigyarto Laszlo,M40,43.2,10.936709,NaN,1.76,3.55,C
61,62,Prague17,Jaroslav Valeri n,MAM,54.1,11.116438,NaN,1.63,3.55,C
62,63,Prague17,Ale? Kuchynka,M45,48.8,11.665339,NaN,1.66,3.56,C
63,64,Prague17,Bradley Selmes,MAM,20.7,12.420000,ciclista 5h,1.69,3.56,C
64,65,Prague17,Frederic Bonningues,M40,54.2,11.782609,NaN,1.69,3.59,C
65,66,Prague17,Barry Sacher,M45,60.3,11.708738,NaN,1.88,3.62,C
66,67,Prague17,Michal korchan Michal,MAM,48.5,11.022727,ciclista 3h,1.93,3.64,C
67,68,Prague17,Branislav Jacko,MAM,34.3,11.307692,NaN,1.74,3.64,C
68,69,Prague17,Joost Saanen,MAM,59.1,10.910769,NaN,1.75,3.65,C
69,70,Prague17,marek kolba,MAM,41.6,12.235294,NaN,1.80,3.67,C
70,71,Prague17,Roy Bruhn,M45,87.0,11.472527,NaN,1.81,3.68,D
71,72,Prague17,Martin Bo Meyer,M50,24.2,11.523810,ciclista 3h,1.76,3.69,D
72,73,Prague17,Lucie Zona,WAM,52.3,11.708955,NaN,1.94,3.69,D
73,74,Prague17,Pavel Szappanos,NaN,53.6,12.711462,NaN,-,3.75,D
74,75,Prague17,Radim Rimanek,MAM,66.7,11.566474,NaN,1.90,3.76,D
75,76,Prague17,Piers Ronan,MAM,23.9,12.050420,ciclista 4h,1.85,3.78,D
76,77,Prague17,Michal Karhan,MAM,40.3,8.337931,ciclista 5h,1.94,3.80,D
77,78,Prague17,Luk ? Pe?iva,MAM,30.6,11.060241,NaN,1.97,3.87,D
78,79,Prague17,Chris Smith,MAM,28.0,11.200000,NaN,1.97,3.89,D
79,80,Prague17,Martin Werner,MAM,53.9,11.802920,NaN,1.98,3.90,D
80,81,Prague17,C‚dou Gatto,NaN,38.1,11.043478,NaN,-,3.90,D
81,82,Prague17,Nathan Khan,MAM,35.6,11125.000000,NaN,2.05,3.92,D
82,83,Prague17,Stefano Vegliani,M55,50.0,10.830325,NaN,2.02,3.93,D
83,84,Prague17,Andrej Madliak,M40,33.6,10.130653,ciclista 3h,1.94,3.93,D
84,85,Prague17,Yoi Ohsako,M40,55.4,11.043189,NaN,1.94,3.94,D
85,86,Prague17,Simon Dunn,M45,33.2,11.066667,NaN,2.05,3.95,D
86,87,Prague17,Pavel ?imek,M40,17.9,10.848485,ciclista 5h,2.05,3.98,D

In [4]:
df1.shape

(87, 10)

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 10 columns):
id               87 non-null int64
Marathon         87 non-null object
Name             87 non-null object
Category         81 non-null object
km4week          87 non-null float64
sp4week          87 non-null float64
CrossTraining    13 non-null object
Wall21           87 non-null object
MarathonTime     87 non-null float64
CATEGORY         87 non-null object
dtypes: float64(3), int64(1), object(6)
memory usage: 6.9+ KB

In [6]:
df1.columns

Index(['id', 'Marathon', 'Name', 'Category', 'km4week', 'sp4week',
       'CrossTraining', 'Wall21', 'MarathonTime', 'CATEGORY'],
      dtype='object')

In [7]:
df1.describe(percentiles=[0.1,0.25,0.5,0.75,0.9])

              id     km4week       sp4week  MarathonTime
count  87.000000   87.000000     87.000000     87.000000
mean   44.000000   62.347126    139.840706      3.319080
std    25.258662   26.956019   1191.427864      0.376923
min     1.000000   17.900000      8.031414      2.370000
10%     9.600000   29.560000     10.926333      2.852000
25%    22.500000   44.200000     11.498168      3.045000
50%    44.000000   58.800000     12.163424      3.320000
75%    65.500000   77.500000     12.854036      3.605000
90%    78.400000   98.660000     13.637509      3.878000
max    87.000000  137.500000  11125.000000      3.980000

In [8]:
df1[df1.duplicated()].sum()

id               0.0
Marathon         0.0
Name             0.0
Category         0.0
km4week          0.0
sp4week          0.0
CrossTraining    0.0
Wall21           0.0
MarathonTime     0.0
CATEGORY         0.0
dtype: float64

In [9]:
df1.isna().sum()

id                0
Marathon          0
Name              0
Category          6
km4week           0
sp4week           0
CrossTraining    74
Wall21            0
MarathonTime      0
CATEGORY          0
dtype: int64

In [10]:
df1['Name'].nunique()

86

In [14]:
imp = Imputer(missing_values = 'NaN', strategy='most_frequent', axis=0)
#df1['Category'] = imp.fit_transform(df1[['Category']]).ravel()
#imp = imp.fit(df1[:,3:])
imp.fit(df1)
#df1 = pd.DataFrame(data=imp.transform(df1), columns=df1.columns)
df1.head()

ValueError: could not convert string to float: 'D'

In [15]:
values=df1['Name']
label_encoder=LabelEncoder()
integer_encoded_1=label_encoder.fit_transform(values)
print(integer_encoded_1)

[ 4 73 59 13 50 18 80 31 80 85 52 35 81 37 19 16 42 17 29 82 70 38  8 39
 23 32  9 66 21 33 47 64 20 26 67 30 49 15  7 43 14 46 79 22 12 36 44 61
 75 62 72 41 48 27  0 28 60 58 53 25 78 34  1  5 24  3 57  6 40 84 74 54
 45 68 71 69 56 51 10 55 11 63 77  2 83 76 65]

In [21]:
LabelEncoder.transform?
#le.fit_transform

In [17]:
Y=df1['Category']
le=LabelEncoder()
Y1=le.fit_transform(Y)
df1['Category_Enco']=Y1
df1.isna().sum()

TypeError: '<' not supported between instances of 'str' and 'float'

In [16]:
Imputer?

In [32]:
Marathon_enco=pd.get_dummies(df1.Marathon,prefix='Marathon').iloc[:,0:]
df1=pd.concat([df1,Marathon_enco],axis=1)
df1=df1.drop('Marathon',axis=1)

In [33]:
#Name_enco=pd.get_dummies(df1.Name,prefix='Name').iloc[:,0:]
#df1=pd.concat([df1,Name_enco],axis=1)
df1=df1.drop('Name',axis=1)
Category_enco=pd.get_dummies(df1.Category,prefix='Category').iloc[:,0:]
df1=pd.concat([df1,Category_enco],axis=1)
df1=df1.drop('Category',axis=1)
Cross_enco=pd.get_dummies(df1.CrossTraining,prefix='CrossTraining').iloc[:,0:]
df1=pd.concat([df1,Cross_enco],axis=1)
df1=df1.drop('CrossTraining',axis=1)
CATEGORY_enco=pd.get_dummies(df1.CATEGORY,prefix='CATEGORY').iloc[:,0:]
df1=pd.concat([df1,CATEGORY_enco],axis=1)
df1=df1.drop('CATEGORY',axis=1)
df1

,id,km4week,sp4week,Wall21,MarathonTime,Marathon_Prague17,Category_M40,Category_M45,Category_M50,Category_M55,...,Category_WAM,CrossTraining_ciclista 13h,CrossTraining_ciclista 1h,CrossTraining_ciclista 3h,CrossTraining_ciclista 4h,CrossTraining_ciclista 5h,CATEGORY_A,CATEGORY_B,CATEGORY_C,CATEGORY_D
0,1,132.8,14.434783,1.16,2.37,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,2,68.6,13.674419,1.23,2.59,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,3,82.7,13.520436,1.30,2.66,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,4,137.5,12.258544,1.32,2.68,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
4,5,84.6,13.945055,1.36,2.74,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
5,6,42.2,13.612903,1.32,2.78,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
6,7,89.0,12.594340,1.38,2.81,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,8,106.0,12.694611,1.41,2.84,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
8,9,70.0,13.770492,1.38,2.83,1,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0
9,10,84.2,13.365079,1.35,2.86,1,0,1,0,0,...,0,0,0,0,0,0,1,0,0,0
10,11,93.5,13.200000,1.42,2.87,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
11,12,65.7,13.362712,1.40,2.87,1,0,0,1,0,...,0,0,0,0,0,0,1,0,0,0
12,13,53.5,14.078947,1.37,2.88,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,0
13,14,84.4,13.836066,1.41,2.88,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
14,15,76.8,12.943820,1.44,2.89,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
15,16,76.1,14.970492,1.45,2.90,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
16,17,112.3,12.594393,1.44,2.91,1,0,0,0,1,...,0,1,0,0,0,0,1,0,0,0
17,18,49.7,14.336538,1.44,2.91,1,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
18,19,84.5,12.549505,1.45,2.93,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
19,20,76.7,8.031414,1.41,2.94,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
20,21,94.5,11.886792,1.45,2.99,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
21,22,67.3,13.239344,1.50,3.04,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
22,23,59.4,12.638298,1.50,3.05,1,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
23,24,66.1,12.128440,1.48,3.09,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
24,25,67.4,12.878981,1.52,3.10,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
25,26,23.8,13.471698,-,3.11,1,0,0,0,0,...,0,0,0,0,0,1,0,1,0,0
26,27,129.6,12.188088,1.54,3.12,1,0,0,0,0,...,1,0,0,0,0,0,0,1,0,0
27,28,82.4,11.771429,1.52,3.14,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
28,29,51.6,13.008403,1.50,3.15,1,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0
29,30,104.9,11.720670,1.57,3.16,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,58,36.3,11.647059,1.72,3.51,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
58,59,22.7,12.728972,1.67,3.52,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
59,60,45.2,11.024390,1.77,3.52,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
60,61,43.2,10.936709,1.76,3.55,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
61,62,54.1,11.116438,1.63,3.55,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
62,63,48.8,11.665339,1.66,3.56,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
63,64,20.7,12.420000,1.69,3.56,1,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
64,65,54.2,11.782609,1.69,3.59,1,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
65,66,60.3,11.708738,1.88,3.62,1,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
66,67,48.5,11.022727,1.93,3.64,1,0,0,0,0,...,0,0,0,1,0,0,0,0,1,0
67,68,34.3,11.307692,1.74,3.64,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
68,69,59.1,10.910769,1.75,3.65,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
69,70,41.6,12.235294,1.80,3.67,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
70,71,87.0,11.472527,1.81,3.68,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
71,72,24.2,11.523810,1.76,3.69,1,0,0,1,0,...,0,0,0,1,0,0,0,0,0,1
72,73,52.3,11.708955,1.94,3.69,1,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
73,74,53.6,12.711462,-,3.75,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
74,75,66.7,11.566474,1.90,3.76,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
75,76,23.9,12.050420,1.85,3.78,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
76,77,40.3,8.337931,1.94,3.80,1,0,0,0,0,...,0,0,0,0,0,1,0,0,0,1
77,78,30.6,11.060241,1.97,3.87,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
78,79,28.0,11.200000,1.97,3.89,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
79,80,53.9,11.802920,1.98,3.90,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
80,81,38.1,11.043478,-,3.90,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
81,82,35.6,11125.000000,2.05,3.92,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
82,83,50.0,10.830325,2.02,3.93,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
83,84,33.6,10.130653,1.94,3.93,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,1
84,85,55.4,11.043189,1.94,3.94,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
85,86,33.2,11.066667,2.05,3.95,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,1
86,87,17.9,10.848485,2.05,3.98,1,1,0,0,0,...,0,0,0,0,0,1,0,0,0,1

In [34]:
Y=['MarathonTime']
X=[i for i in df1 if i not in Y]

In [37]:
from sklearn.cross_validation import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=123)
print("Training feature set size:",X_train.shape)
print("Test feature set size:",X_test.shape)
print("Training variable set size:",Y_train.shape)
print("Test variable set size:",Y_test.shape)

C:\Users\SHALINI\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

ValueError: Found input variables with inconsistent numbers of samples: [20, 1]

In [36]:
from sklearn.linear_model import LinearRegression
from sklearn import metrics
lm = LinearRegression()
lm.fit(X_train,Y_train)

NameError: name 'X_train' is not defined

In [35]:
print("The intercept term of the linear model:", lm.intercept_)
print("The coefficients of the linear model:", lm.coef_)

NameError: name 'lm' is not defined